worth:
  uploadPath: ${worth.uploadPath}
#spring
spring:
  application:
    name: ${spring.application.name}
  jackson:
    date-format: ${spring.application.jackson.dateFormat}
    time-zone: ${spring.application.jackson.timeZone}
  datasource:
    type: ${spring.datasource.type}
    driverClassName: ${spring.datasource.driverClassName}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  cache:
    type: ${spring.cache.type}
  redis:
    database: ${spring.redis.database} #Redis数据库索引（默认为0）
    host: ${spring.redis.host} #Redis服务器地址
    port: ${spring.redis.port} #Redis服务器连接端口
    password: ${spring.redis.password}
    timeout: ${spring.redis.timeout} #连接超时时间（毫秒）
server:
  port: ${server.port}

mybatis-plus:
  mapper-locations: ${mybatisPlus.mapperLocations}
  typeAliasesPackage: ${mybatisPlus.typeAliasesPackage}
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: ${mybatisPlus.globalConfig.idType}
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: ${mybatisPlus.globalConfig.fieldStrategy}
    #驼峰下划线转换
    db-column-underline: ${mybatisPlus.globalConfig.dbColumnUnderline}
    #刷新mapper 调试神器
    refresh-mapper: ${mybatisPlus.globalConfig.refreshMapper}
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: ${mybatisPlus.configuration.mapUnderscoreToCamelCase}
    log-impl: ${mybatisPlus.configuration.logImpl}
    cache-enabled: ${mybatisPlus.configuration.cacheEnabled}

aliyun:
  oss:
    accessKeyId: ${aliyun.oss.accessKeyId}
    accessKeySecret: ${aliyun.oss.accessKeySecret}
    endPoint: ${aliyun.oss.endPoint}
    bucketName: ${aliyun.oss.bucketName}
    publicBucketName: ${aliyun.oss.publicBucketName}

ignore:
  urls:
    - /oauth/**
    - /swagger-resources/**
    - /swagger-ui.html
    - /v2/api-docs
    - /swagger/api-docs
    - /webjars/**
    - /file/download
    - /druid/**

logging:
  #  path: C:/logs
#  level:
#    com.baomidou: debug
#    org.springframework.web: error
#    org.springframework.security: DEBUG
#    cn.worth: DEBUG


#Redis 缓存时长
redis:
  cache:
    expiration: 3600

swagger:
  authorization:
    key-name: ${swagger.authorization.keyName}
  title: ${swagger.title}
  base-package: ${swagger.basePackage}
  exclude-path: ${swagger.excludePath}
  description: ${swagger.description}
